import { CardGridSkeleton } from "@/components/card-grid-skeleton";
import { ImageListStreamed } from "@/components/image-list-streamed";
import { getImagesStreamed } from "@/lib/db/api";
import { unstable_noStore as noStore } from "next/cache";
import { Suspense } from "react";

export const dynamic = "force-dynamic";

export default function Home({
  searchParams,
}: {
  searchParams: { q?: string };
}) {
  noStore();

  return (
    <main className="p-8 space-y-4">
      <h1 className="font-medium text-2xl">
        Semantic Image Search (using Vercel AI SDK)
      </h1>
      <p>
        This demo showcases how to use the Vercel AI SDK to build semantic
        search applications. Try it out by searching for an image. Your query
        will be embedded and then compared against the embedded image titles and
        descriptions (generated by GPT-4o).
      </p>
      <div className="border-border border-t pt-4 space-y-4">
        <Suspense fallback={<CardGridSkeleton />}>
          <ImageList query={searchParams.q} />
        </Suspense>
      </div>
    </main>
  );
}

const ImageList = async ({ query }: { query?: string }) => {
  const { images, status } = await getImagesStreamed(query);

  return <ImageListStreamed images={images} status={status} />;
};
