"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CkNni01Hrgr
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardContent, Card } from "@/components/ui/card";
import { DBImage } from "@/lib/db/schema";
import Image from "next/image";
import { useState } from "react";

export function ImageCard({
  image,
  similarity,
}: {
  image: DBImage;
  similarity?: number;
}) {
  const [show, setShow] = useState(false);
  return (
    <Card
      className="w-full max-w-md"
      onMouseEnter={() => setShow(true)}
      onMouseLeave={() => setShow(false)}
    >
      <CardContent className="space-y-4 p-4">
        {show ? (
          <>
            <div>
              <h3 className="text-xl font-bold">{image.title}</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                {image.description.length > 150
                  ? image.description.slice(0, 150) + "..."
                  : image.description}
              </p>
            </div>
            <div className="flex flex-wrap gap-2 max-h-10">
              {image.vibes.slice(0, 3).map((tag, i) => (
                <span
                  key={tag + "-" + i}
                  className="text-xs rounded-full bg-gray-100 px-3 py-1 font-medium text-gray-800 dark:bg-gray-800 dark:text-gray-200"
                >
                  {tag}
                </span>
              ))}
            </div>
          </>
        ) : (
          <Image
            alt={image.title}
            className="h-[200px] w-full rounded-t-lg object-cover"
            height="200"
            src={image.path}
            style={{
              aspectRatio: "400/200",
              objectFit: "cover",
            }}
            width="400"
          />
        )}
        <h4>{similarity}</h4>
      </CardContent>
    </Card>
  );
}
